apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:qAK//t/hQE7H2AihDHUkNWdBiX2r4uPx,iv:/s62l4y1s8rHSG17ZX9E8voE/HDPCfKl4N3VKV8jyPo=,tag:7EejAA57JeL8PUkEW8BHEA==,type:str]
    admin-user: ENC[AES256_GCM,data:9eGlJ7CFEovYBW60,iv:YJ0ArQ09yA6UyGSkSzZcYhBv81WRktzzYoGkvkJHxVQ=,tag:5/Ln0P6bPmmJgqSYLl2O1A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-admin-creds
    namespace: observability
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NGM4RU5XYVh4MGxJSzc5
            YjhwM1c0eTJoaFduRW1uN1VGcTYwTUlRNWtrCmJWT2NDZmRCTGZrTjI3c29IYWJO
            dWFPSEptTHV4VHFVYzRYaEV0QWdMcDgKLS0tIHJibU1vc1RnM2o5ejd6M0dhL0xh
            SlExNitxdHQ5NG4wdWlRWGZ4NkczMTQKwDt1viqOHBPe903hscuuDpsHWZXWTU3j
            k+1Iv4bJoYdql68gwYZulMF22ZgexqSg6iIg5et7ScTFhCPAxcNxdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T17:15:12Z"
    mac: ENC[AES256_GCM,data:XBJAK3HYprPyou/Epv/i3mRToTNSUqcm/K9Oo4/zcxFWQA2H0zkeZcl+pHDHM+vhUJ3M16M33D9vbGb+BSTkJqBU1e4tx+tWq8AmoeYBQiBg0qxBz5DYkTluzghuT+mAJn7cCNvbNU7zcqBHwag3TthoGZqH9mTeMhszuP5haNI=,iv:wgB2hwDp8ZupMIVSoceaTbXmFd9KIHSJzszTL1LoJ1Y=,tag:pMaA86ZFBl3vFw0al1UgWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
