helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 1h
  chart:
    spec:
      chart: rancher
      version: "2.12.3"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
      interval: 1h
  values:
    replicaCount: 2

    hostname: ranch.heroaero.dev

    ingress:
      enabled: true
      ingressClassName: traefik

      path: /
      pathType: Prefix

      servicePort: 443   # ‚Üê IMPORTANT FIX

      extraAnnotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

      tls:
        source: secret
        secretName: rancher-tls

