apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
spec:
  chart:
    spec:
      chart: portainer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: portainer
      version: 2.33.3
  interval: 10m0s
  values:
    service:
      type: ClusterIP
      httpPort: 9000
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: port.heroaero.net
          paths:
            - path: /
              port: 9000
      tls:
        - hosts:
            - port.heroaero.net
          secretName: portainer-tls
      annotations:
       cert-manager.io/cluster-issuer: letsencrypt-prod 
    persistence:
      enabled: true
      existingClaim: "{{ .Release.Name }}"
      size: 10Gi
      storageClass: longhorn
      accessMode: ReadWriteOnce

