apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
spec:
  chart:
    spec:
      chart: portainer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: portainer
      version: 2.33.3
  interval: 10m0s
  values:
    service:
      type: ClusterIP
      httpPort: 9000
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: port.heroaero.dev
          paths:
            - path: /
              port: 9000
      tls:
        - hosts:
            - port.heroaero.dev
          secretName: portainer-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
          #persistence:
          #enabled: true
          #existingClaim: portainer
          #size: 10Gi
          #storageClass: longhorn
          #accessMode: ReadWriteOnce
          #
