apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 1h
  path: ./kubernetes/apps/metallb/metallb/app
  prune: true
  decryption:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: metallb
  wait: true
