apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: cloudflare-dns-secret
    creationPolicy: Owner
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: cloudflare-dns-secret      # AWS secret name
        property: CF_API_TOKEN
    - secretKey: CF_ZONE_ID
      remoteRef:
        key: cloudflare-dns-secret
        property: CF_ZONE_ID

