apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ./namespace.yaml
  - ./plex/ks.yaml
  - ./mealie/ks.yaml
  - ./linkding/ks.yaml
  - ./homepage/ks.yaml
  - ./home-assistant/ks.yaml
  - ./portainer/ks.yaml
  - ./obsidian/ks.yaml
  - ./jellyfin/ks.yaml
