apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:Q2DIBB9/3wecpCxRykWWm3D/Ihd04i+vukLuYQdkf/LxO8ZvSWKNjk4db2Gjy5WsBe7CmSadR09t16udQVj+JSBinUWmxk5X+cwRGZN0vMbPKJheEb+VZaeR2lfzo0qdrESds8BPKQ6sNlO5hioowkL7jwvG4SrR7IyRZxem5KhZIc2hebFE/1C2IoAKPwlnUhFTbPx11VApBiv9ewRTxOY4X3BcmUqewssLjingnBpyMOm57hGqsoU44FamWIuA+TqEVF9NHNxcttOcV3sJqgCP0OFQu3USNbw1Z+3j7HIV+vdcOwakp2aErJs4V4Ug,iv:ZCD5lDNdn8z4gSgVtzxp1kafTSih7+DgB5Fmh1ph5p0=,tag:suvc4xmEZVGZmJwHXUGvaQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflared-secret
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M3BVOVRLVDFXWlAzQ0lp
            VC9tTktyQXkvZ3FEOHVtNUlxWEcxamlTYmpBCmdQSXUreWlyclZ5bktXZ0M0emVK
            Y0VPRkVjS3FhcUdVVDFTK2ZsVE45eWsKLS0tIGF3dHU4T2tHcEdZSHluNGRPaEhm
            eXZQTmNKWXl6L2YwSUtqZ3N1N2lhbkUKhRV4S5yjCTLkynA/a8+jh1wUtmS49mwE
            5q9RgsuEE7ZFgZ/73GOVRna5D8YbFv5IDvM20+PQpr2IK8O6YfH2Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T15:36:52Z"
    mac: ENC[AES256_GCM,data:268pIiNqoSVD8FgeOVmdnRXxsD8huNlOOexyNp2/HFD+wfCQP9gKyNQn4G7SgrPzzq9RoSPxNsF0kR6mCyH3Ifj12aTT9fR2W7s7UgZxcvP5RSNSAXjCjsmCqQjQWq45Nm2wzS18FC5qO9CcXr8rzz/BVr2Zlrl2l+zgYUE+Dr0=,iv:k5DGLvO08OXHMHMWDcg2XqA/F9QW0pjR/NxdWm5jeBU=,tag:Z8G1gskIdCmG5x492otCWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
