apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-logs
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - vlog.heroaero.dev
      secretName: victoria-logs-tls
  rules:
    - host: vlog.heroaero.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victoria-logs-server
                port:
                  number: 8428   
