apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: web-http
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://plex.heroaero.dev
        - https://mealie.heroaero.dev
        - https://md.heroaero.dev
        - https://homepage.heroaero.dev
        - https://portainer.heroaero.dev
        - https://graf.heroaero.info
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace

