apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: cloudflare-issuer-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore 
  target:
    name: cloudflare-issuer-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-issuer-secret
