apiVersion: v1
data:
    CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:ub1coNeWgLC+ZFQ9i0otaq8NprnTaqlknuIcbdPo/eWMd4ckdRwoHsodWVNDzk6qoubU7L5HYag=,iv:iIxMZO776CaOjuFMa+e9xbZlQSo9g1t7f/EY0pDRQrI=,tag:yfzTN6lM9ilCA9U3qMvtCw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-issuer-secret
    namespace: cert-manager
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ2M0UHdKY3R4ZW0rNkQz
            VFdGVnZKUXRXVlJQKzMzV1FyNVVsVHA2dXhVCkgzejJUMTlUaHFqSHdkR1E2MWx6
            V21YYWpTSWpid0VZRUZ5aFBGYkN4cWcKLS0tIDFydysycGFaRklYem1pVGVzbSt0
            ZWQ5LzV1VjVwRURWcTJwSHk3dGZLaU0KvEsdkxwpSWPh3GmuCr4X9aS793BV5kqn
            Usuhz7Knq4k9sb3pH7uNk8Qw0k2n0t+/rFfTxAIpK0ffVVaDr5To9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T02:58:39Z"
    mac: ENC[AES256_GCM,data:yMLy1zcDH2kphrJy+9/Jfu5kBD7kD0e04GDqnxDsU7hpy9HFSraS9/IHtEtZzRWwigKaYgwcLXIZClgNlmNDI9bKZPQKpXuw56008FgwPoWWcDb0EQrxVfvjafsSXcRnxm1oCm/+g/xk38Vh22RYRYrRSBI1dQAPg6C8dqaxr9I=,iv:UE/H4eW5FJolZmBe6EYbBioHSrcbHcgaHVMHvkwngsU=,tag:SHV6WXOIKrylc5pExai2ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
