apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra1
  namespace: flux-system
spec:
  interval: 30m0s
  # dependsOn:
  # - name: infra-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
