apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/alerts
  - ../../components/nfs-scaler
resources:
  - ./namespace.yaml
  - ./keda/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
