apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./plex-config-pvc.yaml
  - ./plex-tv-pvc.yaml
  - ./plex-movies-pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
