apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:HrG7nLS51ktLoeyokLzcC3UtHckNVBLBXimUPRZViiWmCeFaZQBYHFx/icLgrf50UFXSisKtuHk=,iv:244Gf9J+1YxbTAT2RK78FcLml+9WO5uCzGG+E8TCZYA=,tag:0DVUlvXswCblXndIUkf3Hw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate
    namespace: renovate
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM1RQOXBPMjNsOGdOeDVN
            TGJKMVJYMWlvenRkZTBzOUN6NC9BNWcvUDFNCkJOSURxUmVRUS9MQTRXZHRhVERD
            NndVQWlpOUZmTGZCNGJsZkFTNEhidVEKLS0tIE41N2k4Nzg4QWEwQ2pVSnFhYi9O
            WEI5ZUE4VkoxOUc5NFRTdVRkN1Y5Q3MKktoUK78fZ2bt1C7knMyBN4y7uN2Qwz0/
            3x4deuVz+OmAutJIo2O1eS5fX0OhyDGXShrI2ZSZ30WcgXZ0qfq+Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:33:34Z"
    mac: ENC[AES256_GCM,data:s4XqcpfohNaWiS025PaQX2hzlJ1AGcbyRXMYCQhMaWumI88tommF54rdHuK5rq4/egVHqTfxR+U9Lr7WFqhcULlBYwa5JlEgvcbz1nlFFYtM6VwauIYf/iS55OXGWlfvC33f+BIteTOxS8KeJolWlIXOcS7qSoAABbxXxq0Gtis=,iv:8pdtdWg7bcNgDpbTs6YIdCRJxc/X8YASTqSGRz1lkxk=,tag:iMf8qJB1tfHBFrArIVj+lA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
