apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:qtR5oMepHaelRDbOZ1lF9ClK4giKqUlc7MTb37egATYG2f9G/AlIE9Md9bxqKB7AUrWfSCV2k74=,iv:Ta05qVl8Y8emoSFfT//GgwsepOmcyTsCLqi3Wr/44/I=,tag:viG/Pnm4/bGMZ5JmVJzy0Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrenAxck13bmNKTVhjUUx0
            S1FOWlU5Z3JBbjVEOE9zTklQS1IvR3h5cFMwCjF4cGtZMXp5N2trM0tkemx4d1I3
            S1VUUkVuQTg1M1paU3duSktEZGNHVG8KLS0tIEt1VFBDVVVua2t5czNpNytSV0RH
            Vi91Um9xMk5LL2Y3MUQ4c3k0MytqVmsKPcob3tDj53Sbjb1INHXIUPl3TaXp8dHh
            YPGk0aUnd/rULGqCW5j1YonxGsDBtK71iQZYrSsSZdH1ccVbB458ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T04:33:03Z"
    mac: ENC[AES256_GCM,data:tsbMISHjRSh/bGzIGVKpSakfWwz8zU65PjVE+YOKz22/lQc+POoxi6obUmAwWg1BmwTkwEMpMCZDV/MVmZmyAqiJcEXDJ3xOxbkoYFnjYsrrdOiDAuz8rY71meo2YHcWnGIwzH79xNEOtqh1cd9DtOmAd8kARF0rZYHwft4qP2A=,iv:xPSbhSqByIdOLLU6MhvzjCiIPo9prgzhkUj7u+/mKW4=,tag:eSWjJ4ad+CVvETGRCSCB1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
