apiVersion: v1
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:xBLKQWpKGRKo2o1//4vfR/reP+LwzdynbOJ0Or0AWesofjTVHBpll1MTmkDVofazKKeUdETzyeQ=,iv:hg0hu9OK/rtcA6p2XW/9BG2dAItIR2eHCxgj1Pvdc7o=,tag:1IKnuy3IT3VpwK8agyERCQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate
    namespace: renovate
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTVBEVmV2L0VwK1lZa1Vz
            dW10SXl1a2xHUWp0NmdBNW5uQ0ZSMGJoNFZBCmdEdTQwRjRYa214UFcrMk1mejZH
            a000WUE0elBTUmd0TTlRbmtjeUREU2cKLS0tIFM2eGFCbWlGclJqZzZBd2dsY08z
            UURqOHRyeHI5V1ZVbTVHeVYzdUphOFEKa6De9l6gbNFZhacUKvgN/PFzja2j4mMV
            q4d5qc11AoTmEeWQ5KMawMVlQX32AmQdEFYgurjgOtqD+C9FnBlUOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:23:17Z"
    mac: ENC[AES256_GCM,data:/g9YjUTCTkQkoFmw1bW9KgafAg5wi8fBrAIgsaQ506biclu5vTv7tRwWfPkSVnCxV3+RrEtLEUaETmoUCQPVC2cnWpS20qmMUWoR1Z+isQmeEgCCNt48a1ptaAZD+u4VrretJB/lSlk32PYsKYzTHuHIrVzgaMgowB4Gjwlehgs=,iv:CeK8tT4xYZ4ZNDgDpRDPpCA8WaymGjia0mpxcw/p2RQ=,tag:E+rWYaLM1WN+KGGAIPjVMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
