apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:gkqJvhakUSud+5RHzIwFOtoELl3GcYyvNcPbTv3rPcfejSm4qA8V2hbhG+9/1QRvc7W+3K+dQQE=,iv:D6vIR9H2jlKn3Fu4g8/VsSQVvVhbqrNmiiOJw2CB9Zo=,tag:jx5FlHFZRF34ldujZxbsKQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArck9WeGh6VCsrS1J5Zi9z
            bkpMOXdIZGpETlh0ZHJCWkZtT25jMnhWWkgwCjJ4cHE2UEd1OFltVC9HK2dwM3k2
            eWZRM2NySE9WODB0ZHVOOHB4M0QyakUKLS0tIFV1UXRyOHJJOGxTUTY1R3BNTmFt
            N1VEWTJFMTVnVjhWYjR0RkcxWlBVc28Ku4mwifCjZV4I5hUy9cRyFaSuoY93yYZ2
            5KEjQVNaXUJGbtwzvl4FZgovYT/TGcWJFZmTQva5Ax741y34QNSV9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T20:04:20Z"
    mac: ENC[AES256_GCM,data:IcahNkBcsse7j6e2D67Hl4N1VrB2Yc6HUd885N1kfIA830EtVG182dE86JU9mkqT77TGlQjDzgb7fg2paneYf2Ox5NCZK97d1+rdLKV9Jm6houL/9F4FptIISnu1BOkyNXtRwtQR+EGtouHaWj/agaD9au6x5aAKbBOQ09JCOzs=,iv:fmRzilllcYiuGuqsTsJeDtvfcCXs6ncM/Lh3EiddCOg=,tag:Ac11oZCz7UqSBB7MGr3FyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
