apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:QJneNSOOSfNBUOwMWb9Vi/fGOVjdVIzHUtvuFw==,iv:QjYXyuBCgsYeyD/eproA5NtxtXglSW2y3HxgEn9LHs8=,tag:81ibJfb+nU7LbeQyFMechA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:XYTfAquMefcK9qvdgyI38MDNUFABxKksHFkkiXnFrapvBH57MjZaZc9EKikuhdLSP4c9dgD1OiY=,iv:uytw5sjWpMXRgJBk9Ugvvh5JGjPM+TjOtSmF5P1WzSQ=,tag:xwxqBiwVmn4C7c6qgsdEoQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: aws-secret
    namespace: external-secrets
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZktZNFNYeHQ5UVVjZnRZ
            WEdvS3ZLWTBHN2E5eFJ2akl0Ty9wVzgxNEFRCnJnYy9tMG9Bb1orZkt0cWExNEQ2
            REdEbmlSZDdYZkRsNVMyWEw2SjB2REUKLS0tIHNHOWQwdC9TYkRyNXp3Q3pIOUdU
            V3IxVE1WNkVPdURRTE1sZnpEdk5JYWMK/EMqoKShSMIq5B/7B6lDkHHvRa6IktoP
            Lwuv1nEWYU4/k8R7I5b9BXki7ZQGW/4Jboh7drdjsT73Y7XaTfdHZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T03:59:43Z"
    mac: ENC[AES256_GCM,data:uyYGHNSPVj3Cl1sCFmG/lMMIh30SeDkJiaYESChfWHrg4SJIBInxtjRD3JJ02oXSoce2s36dlJVpLysUUQX7TRVeJY+gKVoFvdxpZ6lPhsDqAtcM6IEJL6fJrFoyVhj9sz4KIjFV93wqVLrAsnHTEv7yxTnXC2oEPGllHr0OHHY=,iv:ik113qSsTe9C5oUrrQunRLrVBi3O39CvfVRGHTNqvfM=,tag:fmr2VLra8yugIrp1cxCi7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
