apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rancher
spec:
  interval: 1h
  path: ./kubernetes/apps/rancher/rancher/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cattle-system
  wait: false
