apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Optional: force redirect https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - mealie.heroaero.dev
      secretName: mealie-tls 
  rules:
    - host: mealie.heroaero.dev
      http:
        paths:
          - backend:
              service:
                name: mealie
                port:
                  number: 9001
            path: /
            pathType: Prefix
