apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: homepage-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    name: homepage
    apiVersion: apps/v1
    kind: Deployment

  minReplicaCount: 3
  maxReplicaCount: 10

  cooldownPeriod: 30

  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        # scale up when CPU usage > 40% of limit
        value: "40"

    - type: memory
      metricType: Utilization
      metadata:
        # scale up when memory usage > 50% of limit
        value: "50"

