apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: alertmanager
spec:
  providerRef:
    name: alertmanager
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: HelmChart
      name: "*"
    - kind: OCIRepository
      name: "*"
    - kind: ImageRepository
      name: "*"
    - kind: ImagePolicy
      name: "*"
    - kind: ImageUpdateAutomation
      name: "*"
  exclusionList:
    - "error.*lookup.*github"
    - "dial.*tcp.*timeout"
    - "waiting.*socket"
  suspend: false

