services:
  warden:
    container_name: vaultwarden
    image: vaultwarden/server:testing-alpine
    ports:
      - 8089:80
    volumes:
      - /srv/docker/vaultwarden/data:/data

    restart: unless-stopped
    networks:
      - homelab
  
networks:
  homelab:
    driver: bridge
